# Generated by Django 4.2.20 on 2025-05-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PollitosACL_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campoUno', models.CharField(max_length=100)),
                ('campoDos', models.CharField(max_length=100)),
                ('campoTres', models.CharField(max_length=100)),
            ],
        ),
    ]
